model_name = "3kbps"
sample_rate = 16000
model_version = "v1"

[network_config]
feature_dim = 128
compress_rates = [6, 4, 4]
encoder_dims = [24, 48, 96, 192]
encoder_depths = [1, 1, 1, 2]
decode_rates = [4, 4, 3, 2]
decoder_dims = [512, 256, 96, 48, 24]
decoder_depths = [3, 3, 2, 1, 1]
base_unit = 'normal'
use_norm = true
use_snake_act = true
decoder_last_layer = 'legacy'
vq_config = { name = "super_fsq", levels = [9, 9, 9, 7, 7, 7], noise_rate = 0.5 }
en_coder_depth = 3
en_coder_window_size = 400
en_coder_dynamic_pos = true
en_coder_compress_rate = 1
en_coder_cache_size = 0
