class DN:
    # generated by xtract.data.TorchDataset
    id = "data_id"  # str

    # data attr
    name = "data_name"  # str
    # data = "data"
    audio = "audio"  # ndarray
    txt = "txt"  # str
    # LABEL = "label"

    # other
